// Source code page: loads code-snapshot.json (generated by
// scripts/gen_code_snapshot.py from the real repo source) and renders a
// model picker + language tabs + syntax-highlighted, copyable code block.

(function () {
  "use strict";

  const modelListEl = document.getElementById("model-list");
  const langTabsEl = document.getElementById("lang-tabs");
  const titleEl = document.getElementById("code-title");
  const descriptionEl = document.getElementById("code-description");
  const pathEl = document.getElementById("code-path");
  const outputEl = document.getElementById("code-output");
  const copyButton = document.getElementById("copy-button");

  const LANG_ORDER = ["python", "cpp", "rust", "csharp"];

  let groups = [];
  let activeGroupId = null;
  let activeLang = "python";

  function render() {
    const group = groups.find((g) => g.id === activeGroupId);
    if (!group) return;

    for (const child of modelListEl.children) {
      child.setAttribute("aria-current", String(child.dataset.groupId === activeGroupId));
    }

    titleEl.textContent = group.title;
    descriptionEl.textContent = group.description;

    const availableLangs = LANG_ORDER.filter((l) => group.languages[l]);
    if (!availableLangs.includes(activeLang)) {
      activeLang = availableLangs[0];
    }

    langTabsEl.innerHTML = "";
    for (const lang of availableLangs) {
      const tab = document.createElement("button");
      tab.type = "button";
      tab.className = "lang-tab";
      tab.setAttribute("role", "tab");
      tab.setAttribute("aria-selected", String(lang === activeLang));
      tab.textContent = group.languages[lang].label;
      tab.addEventListener("click", () => {
        activeLang = lang;
        render();
      });
      langTabsEl.appendChild(tab);
    }

    const entry = group.languages[activeLang];
    pathEl.textContent = entry.paths.join(", ");
    outputEl.innerHTML = window.QkHighlight
      ? window.QkHighlight.highlight(entry.code, activeLang)
      : entry.code;
  }

  function selectGroup(id) {
    activeGroupId = id;
    render();
  }

  async function init() {
    let data;
    try {
      const response = await fetch("code-snapshot.json");
      data = await response.json();
    } catch (err) {
      titleEl.textContent = "Could not load code-snapshot.json";
      descriptionEl.textContent = String(err);
      return;
    }
    groups = data.groups;

    modelListEl.innerHTML = "";
    for (const group of groups) {
      const item = document.createElement("button");
      item.type = "button";
      item.className = "model-item";
      item.setAttribute("role", "listitem");
      item.dataset.groupId = group.id;
      item.textContent = group.title;
      item.addEventListener("click", () => selectGroup(group.id));
      modelListEl.appendChild(item);
    }

    selectGroup(groups[0].id);
  }

  copyButton.addEventListener("click", async () => {
    const group = groups.find((g) => g.id === activeGroupId);
    if (!group) return;
    const code = group.languages[activeLang].code;
    try {
      await navigator.clipboard.writeText(code);
      copyButton.textContent = "Copied!";
    } catch {
      copyButton.textContent = "Copy failed";
    }
    setTimeout(() => { copyButton.textContent = "Copy"; }, 1500);
  });

  init();
})();
