//! Loads contracts/vectors/*.json (generated by python/gen_vectors.py from
//! the verified Python reference) and checks the Rust engine reproduces
//! every case within the vector's declared tolerance. Cross-language proof
//! the whole project is built around -- see contracts/README.md.

use std::fs;
use std::path::PathBuf;

use quantkiller::models::{american, binomial, black_scholes, forward_parity, implied_vol, monte_carlo};
use serde_json::Value;

fn repo_root() -> PathBuf {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    loop {
        if dir.join("contracts").join("vectors").is_dir() {
            return dir;
        }
        if !dir.pop() {
            panic!("could not locate contracts/vectors from CARGO_MANIFEST_DIR");
        }
    }
}

fn num(v: &Value, key: &str) -> f64 {
    v.get(key).and_then(|x| x.as_f64()).unwrap_or_else(|| panic!("missing numeric param '{key}'"))
}

fn num_default(v: &Value, key: &str, default: f64) -> f64 {
    v.get(key).and_then(|x| x.as_f64()).unwrap_or(default)
}

fn opt_num(v: &Value, key: &str) -> Option<f64> {
    v.get(key).and_then(|x| x.as_f64())
}

fn is_call(v: &Value) -> bool {
    v.get("option_type").and_then(|x| x.as_str()) == Some("call")
}

fn is_american(v: &Value) -> bool {
    v.get("style").and_then(|x| x.as_str()) == Some("american")
}

#[test]
fn engine_matches_golden_vectors() {
    let dir = repo_root().join("contracts").join("vectors");
    let mut checked_files = 0;
    let mut checked_cases = 0;

    for entry in fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let doc: Value = serde_json::from_str(&fs::read_to_string(&path).unwrap()).unwrap();
        let model = doc["model"].as_str().unwrap();
        checked_files += 1;

        for case in doc["cases"].as_array().unwrap() {
            let name = case["name"].as_str().unwrap();
            let p = &case["params"];
            let expected = &case["expected"];
            let rel_tol = case["tolerance"]["rel"].as_f64().unwrap();
            let abs_tol = case["tolerance"]["abs"].as_f64().unwrap();

            let actual = match model {
                "black_scholes" => Some(black_scholes::price(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "vol"), num(p, "time"), is_call(p))),
                "binomial_crr" => Some(binomial::price(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "vol"), num(p, "time"), is_call(p), is_american(p),
                    p["steps"].as_u64().unwrap() as usize).unwrap()),
                "monte_carlo_gbm" => Some(monte_carlo::price(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "vol"), num(p, "time"), is_call(p), p["paths"].as_u64().unwrap(),
                    p["seed"].as_u64().unwrap(), p["antithetic"].as_bool().unwrap()).unwrap()),
                "implied_vol" => Some(implied_vol::solve(
                    num(p, "price"), num(p, "spot"), num(p, "strike"), num(p, "rate"),
                    num_default(p, "div_yield", 0.0), num(p, "time"), is_call(p)).unwrap()),
                "forward" => Some(forward_parity::forward_price(
                    num(p, "spot"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "time"), opt_num(p, "strike"))),
                "put_call_parity" => Some(forward_parity::parity(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "time"), opt_num(p, "call_price"), opt_num(p, "put_price")).unwrap()),
                "american_baw" => Some(american::baw(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "vol"), num(p, "time"), is_call(p)).unwrap()),
                "american_ju_zhong" => Some(american::ju_zhong(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "vol"), num(p, "time"), is_call(p)).unwrap()),
                "american_bjerksund_1993" => Some(american::bjerksund_1993(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "vol"), num(p, "time"), is_call(p)).unwrap()),
                "american_bjerksund_2002" => Some(american::bjerksund_2002(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "vol"), num(p, "time"), is_call(p)).unwrap()),
                "american_carr_randomization" => Some(american::carr_randomization(
                    num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
                    num(p, "vol"), num(p, "time"), num_default(p, "phases", 64.0) as u32, is_call(p)).unwrap()),
                _ => None, // not yet ported -- not a failure
            };

            let Some(actual) = actual else { continue };
            checked_cases += 1;

            for (field, expected_value) in expected.as_object().unwrap() {
                let expected_value = expected_value.as_f64().unwrap();
                let actual_value = *actual.get(field).unwrap_or_else(|| panic!("{model}/{name}: missing field '{field}'"));
                let allowed = abs_tol + rel_tol * expected_value.abs();
                let diff = (actual_value - expected_value).abs();
                assert!(
                    diff <= allowed,
                    "{model}/{name}.{field}: expected {expected_value}, got {actual_value}, diff {diff} > allowed {allowed}"
                );
            }
        }
    }

    assert!(checked_files >= 11, "expected at least 11 vector files, found {checked_files}");
    assert!(checked_cases > 0, "no vector cases were actually checked");
    println!("checked {checked_cases} cases across {checked_files} vector files");
}
