// Loads contracts/vectors/*.json (generated by python/gen_vectors.py from
// the verified Python reference) and checks the C++ engine reproduces every
// case within the vector's declared tolerance. Cross-language proof the
// whole project is built around -- see contracts/README.md.

#include <cmath>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <optional>
#include <sstream>
#include <string>

#include "quantkiller/json_lite.hpp"
#include "quantkiller/models/american.hpp"
#include "quantkiller/models/binomial.hpp"
#include "quantkiller/models/black_scholes.hpp"
#include "quantkiller/models/forward_parity.hpp"
#include "quantkiller/models/implied_vol.hpp"
#include "quantkiller/models/monte_carlo.hpp"

namespace fs = std::filesystem;
namespace qjson = quantkiller::json;
using namespace quantkiller::models;

namespace {

double num(const qjson::Value& p, const std::string& key) { return p.find(key)->as_number(); }
double num_default(const qjson::Value& p, const std::string& key, double def) {
    const auto* v = p.find(key);
    return (v && v->is_number()) ? v->as_number() : def;
}
std::optional<double> opt_num(const qjson::Value& p, const std::string& key) {
    const auto* v = p.find(key);
    if (v && v->is_number()) return v->as_number();
    return std::nullopt;
}
bool is_call(const qjson::Value& p) { return p.find("option_type")->as_string() == "call"; }
bool is_american(const qjson::Value& p) {
    const auto* v = p.find("style");
    return v && v->as_string() == "american";
}

std::optional<std::map<std::string, double>> price_via_model(const std::string& model, const qjson::Value& p) {
    if (model == "black_scholes") {
        return black_scholes_price(num(p, "spot"), num(p, "strike"), num(p, "rate"),
            num_default(p, "div_yield", 0.0), num(p, "vol"), num(p, "time"), is_call(p));
    }
    if (model == "binomial_crr") {
        return binomial_price(num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
            num(p, "vol"), num(p, "time"), is_call(p), is_american(p), static_cast<int>(num(p, "steps")));
    }
    if (model == "monte_carlo_gbm") {
        return monte_carlo_price(num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
            num(p, "vol"), num(p, "time"), is_call(p), static_cast<int>(num(p, "paths")),
            static_cast<std::uint64_t>(num(p, "seed")), p.find("antithetic")->as_bool());
    }
    if (model == "implied_vol") {
        return implied_vol_solve(num(p, "price"), num(p, "spot"), num(p, "strike"), num(p, "rate"),
            num_default(p, "div_yield", 0.0), num(p, "time"), is_call(p));
    }
    if (model == "forward") {
        return forward_price(num(p, "spot"), num(p, "rate"), num_default(p, "div_yield", 0.0), num(p, "time"), opt_num(p, "strike"));
    }
    if (model == "put_call_parity") {
        return put_call_parity(num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
            num(p, "time"), opt_num(p, "call_price"), opt_num(p, "put_price"));
    }
    if (model == "american_baw") {
        return baw_price(num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
            num(p, "vol"), num(p, "time"), is_call(p));
    }
    if (model == "american_ju_zhong") {
        return ju_zhong_price(num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
            num(p, "vol"), num(p, "time"), is_call(p));
    }
    if (model == "american_bjerksund_1993") {
        return bjerksund_1993_price(num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
            num(p, "vol"), num(p, "time"), is_call(p));
    }
    if (model == "american_bjerksund_2002") {
        return bjerksund_2002_price(num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
            num(p, "vol"), num(p, "time"), is_call(p));
    }
    if (model == "american_carr_randomization") {
        return carr_randomization_price(num(p, "spot"), num(p, "strike"), num(p, "rate"), num_default(p, "div_yield", 0.0),
            num(p, "vol"), num(p, "time"), static_cast<int>(num_default(p, "phases", 64.0)), is_call(p));
    }
    return std::nullopt;
}

fs::path find_repo_root(fs::path dir) {
    while (true) {
        if (fs::is_directory(dir / "contracts" / "vectors")) return dir;
        if (!dir.has_parent_path() || dir.parent_path() == dir) {
            throw std::runtime_error("could not locate contracts/vectors");
        }
        dir = dir.parent_path();
    }
}

}  // namespace

int main() {
    const fs::path root = find_repo_root(fs::current_path());
    const fs::path vectors_dir = root / "contracts" / "vectors";

    int checked_files = 0;
    int checked_cases = 0;
    int failures = 0;

    for (const auto& entry : fs::directory_iterator(vectors_dir)) {
        if (entry.path().extension() != ".json") continue;
        std::ifstream in(entry.path());
        std::ostringstream ss;
        ss << in.rdbuf();
        qjson::Value doc = qjson::Value::parse(ss.str());
        const std::string model = doc.find("model")->as_string();
        checked_files++;

        for (const auto& case_v : doc.find("cases")->as_array()) {
            const std::string name = case_v.find("name")->as_string();
            const qjson::Value& params = *case_v.find("params");
            const qjson::Value& expected = *case_v.find("expected");
            const double rel_tol = case_v.find("tolerance")->find("rel")->as_number();
            const double abs_tol = case_v.find("tolerance")->find("abs")->as_number();

            auto actual_opt = price_via_model(model, params);
            if (!actual_opt.has_value()) continue;  // not yet ported -- not a failure
            checked_cases++;
            const auto& actual = *actual_opt;

            for (const auto& [field, expected_value_v] : expected.as_object()) {
                const double expected_value = expected_value_v.as_number();
                auto it = actual.find(field);
                if (it == actual.end()) {
                    std::cout << "FAIL " << model << "/" << name << "." << field << ": missing field\n";
                    failures++;
                    continue;
                }
                const double actual_value = it->second;
                const double allowed = abs_tol + rel_tol * std::fabs(expected_value);
                const double diff = std::fabs(actual_value - expected_value);
                if (diff > allowed) {
                    std::cout << "FAIL " << model << "/" << name << "." << field
                              << ": expected " << expected_value << ", got " << actual_value
                              << ", diff " << diff << " > allowed " << allowed << "\n";
                    failures++;
                }
            }
        }
    }

    std::cout << "checked " << checked_cases << " cases across " << checked_files << " vector files\n";
    if (failures > 0) {
        std::cout << failures << " FAILURES\n";
        return 1;
    }
    if (checked_files < 11) {
        std::cout << "expected at least 11 vector files, found " << checked_files << "\n";
        return 1;
    }
    std::cout << "all vectors passed\n";
    return 0;
}
