using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using QuantKiller.Cli;
using Xunit;

namespace QuantKiller.Tests;

/// <summary>
/// Loads contracts/vectors/*.json (generated by python/gen_vectors.py from
/// the verified Python reference) and checks the C# engine reproduces every
/// case within the vector's declared tolerance. This is the cross-language
/// proof the whole project is built around — see contracts/README.md.
/// </summary>
public class VectorTests
{
    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null && !Directory.Exists(Path.Combine(dir.FullName, "contracts", "vectors")))
        {
            dir = dir.Parent;
        }
        if (dir == null) throw new DirectoryNotFoundException("could not locate contracts/vectors from test output directory");
        return dir.FullName;
    }

    public static IEnumerable<object[]> VectorFiles()
    {
        var root = FindRepoRoot();
        var dir = Path.Combine(root, "contracts", "vectors");
        foreach (var file in Directory.GetFiles(dir, "*.json").OrderBy(f => f))
        {
            yield return [file];
        }
    }

    [Theory]
    [MemberData(nameof(VectorFiles))]
    public void EngineMatchesGoldenVectors(string path)
    {
        var doc = JsonDocument.Parse(File.ReadAllText(path));
        var root = doc.RootElement;
        var model = root.GetProperty("model").GetString()!;

        if (!ModelRegistry.Models.TryGetValue(model, out var fn))
        {
            // Model not yet ported to C# (e.g. planned Tier B/C) -- not a failure, just not applicable yet.
            return;
        }

        foreach (var caseElement in root.GetProperty("cases").EnumerateArray())
        {
            var name = caseElement.GetProperty("name").GetString();
            var paramsElement = caseElement.GetProperty("params");
            var expected = caseElement.GetProperty("expected");
            var tolerance = caseElement.GetProperty("tolerance");
            var relTol = tolerance.GetProperty("rel").GetDouble();
            var absTol = tolerance.GetProperty("abs").GetDouble();

            var actual = fn(paramsElement);

            foreach (var field in expected.EnumerateObject())
            {
                Assert.True(actual.ContainsKey(field.Name), $"{model}/{name}: missing field '{field.Name}' in C# result");
                var expectedValue = field.Value.GetDouble();
                var actualValue = actual[field.Name];
                var allowed = absTol + relTol * Math.Abs(expectedValue);
                var diff = Math.Abs(actualValue - expectedValue);
                Assert.True(diff <= allowed,
                    $"{model}/{name}.{field.Name}: expected {expectedValue}, got {actualValue}, diff {diff} > allowed {allowed}");
            }
        }
    }
}
